// Generated by CoffeeScript 1.3.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define([], function() {
    var Indexer;
    return Indexer = (function() {

      function Indexer() {
        this.unique = [];
        this.indices = [];
        this.map = {};
      }

      Indexer.prototype.add = function(obj) {
        var key;
        key = JSON.stringify(obj);
        if (__indexOf.call(this.map, key) < 0) {
          this.map[key] = this.unique.length;
          this.unique.push(obj);
        }
        return this.map[key];
      };

      return Indexer;

    })();
  });

}).call(this);
