// Generated by CoffeeScript 1.3.3
(function() {
  if(typeof define!=='function'){var define = require('amdefine')(module)};

  define([], function() {
    var Indexer;
    return Indexer = (function() {

      function Indexer() {
        this.unique = [];
        this.indices = [];
        this.map = {};
      }

      Indexer.prototype.add = function(obj) {
        var key;
        key = JSON.stringify(obj);
        if (!(key in this.map)) {
          this.map[key] = this.unique.length;
          this.unique.push(obj);
        }
        return this.map[key];
      };

      return Indexer;

    })();
  });

}).call(this);
