// Generated by CoffeeScript 1.3.3
(function() {
  var Indexer;

  Indexer = require('./indexer');

  describe('Indexer', function() {
    beforeEach(function() {
      return this.it = new Indexer;
    });
    it('supports integers', function() {
      var x, _i, _len, _ref;
      _ref = [1, 2, 3, 1];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        x = _ref[_i];
        this.it.add(x);
      }
      return this.it.unique.should.eql([1, 2, 3]);
    });
    it('supports strings', function() {
      var x, _i, _len, _ref;
      _ref = ['apple', 'banana', 'apple', 'orange'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        x = _ref[_i];
        this.it.add(x);
      }
      return this.it.unique.should.eql(['apple', 'banana', 'orange']);
    });
    return it('supports lists', function() {
      var x, _i, _len, _ref;
      _ref = [[1, 2], [3, 4], [1, 2], [3, 4], [4, 3]];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        x = _ref[_i];
        this.it.add(x);
      }
      return this.it.unique.should.eql([[1, 2], [3, 4], [4, 3]]);
    });
  });

}).call(this);
